name: Publish Python 🐛 distribution package 📦 to Test PyPI

on: push

jobs:
  build-n-publish:
    name: Build and publish Python 🐛 dist 📦 to Test PyPI
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        python-version:
        - 3.8
        - 3.7
        os:
        - ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install tox
      run: |
        python -m pip install --upgrade tox
    - name: Initialize tox env
      run: |
        python -m tox -e build-dists --parallel auto --notest
    - name: Build dists
      run: |
        python -m tox -e build-dists --parallel 0
    - name: Publish 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.Test_PyPI_token }}
        repository_url: https://test.pypi.org/legacy/